//
// Created by Nguyễn Đức Quang on 5/6/20.
//

#ifndef CSC213_UTILITY_H
#define CSC213_UTILITY_H

#endif //CSC213_UTILITY_H

#define TIMEOUT 1000

#define USERNAME_LEN 256
#define MESSAGE_LEN 500
#define SERVER_NAME_LEN 256

#define MESS_RECORD_TABLE_SIZE 100
#define NEW_MESSAGE -1
#define OLD_MESSAGE 1
#define MESS_RECORD_ADD_SUCCESS 1
#define MESS_RECORD_ADD_FAIL -1
#define MESS_RECORD_DUPLICATE_ADD -2
#define NUM_OLD_MESSAGES_ALLOW 20
#define MESS_PROCESS_SUCCESSFUL 1
#define MESS_PROCESS_FAIL -1

#define PEER_LIST_TABLE_SIZE 100
#define IN_PEER_LIST 1
#define NOT_IN_PEER_LIST -1
#define PEER_LIST_ADD_SUCCESSFUL 1
#define PEER_LIST_ADD_FAIL -1
#define PEER_LIST_DUPLICATE_ADD -2

#define TYPE_NORMAL 1
#define TYPE_ADD_PEER 2
#define TYPE_REMOVE_PEER 3
#define TYPE_MY_NAME 4

#define MAX_QUEUE_CONNECTION 20
#define LISTENING_TIME_OUT 3600
#define PTHREAD_SET_INIT_CAP 4
#define FALSE 0
#define TRUE 1